sudo: false
dist: xenial
language: python
cache: pip
matrix:
  include:
  - python: '3.6'
    os: linux
  - python: '3.7'
    os: linux
install:
- pip install --upgrade pip codecov
- pip install --upgrade -e .[develop]
script:
- nosetests
after_success:
- codecov
notifications:
  email: false